In [21]:
import pandas as pd

In [20]:
df =  pd.read_excel('data/raw/Operational_Mining_Data.xlsx', sheet_name=None)
equipment_df = df['Equipment_Events']

In [22]:
equipment_df.head()

,Event_ID,Equipment_Name,Event_Time,Event_Type,Status,Meter_Reading,Meter_Unit,Location,Operator_ID,Source_System,Comment
0,EVT0001,TRK-001,01/07/2026 11:00,Idle,Complete,1007.3,hours,Workshop,OP1001,Telemetry-A,NaN
1,EVT0002,TRK002,07/01/2026 04:00 PM,start,Open,1014.6,hours,Workshop,OP1002,Telemetry-A,check sensor
2,EVT0003,truck03,2026/07/01 21:00,Inspection,Complete,1021.9,hours,South Pit,OP1003,Telemetry-A,Normal event
3,EVT0004,EXC001,2026-07-02 02:00:00,start,closed,1029.2,hours,Workshop,OP1004,Telemetry-A,check sensor
4,EVT0005,EXC-02,02/07/2026 07:00,start,Complete,1036.5,mins,South Pit,OP1005,Telemetry-A,NaN

In [7]:
equipment_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Event_ID        46 non-null     object
 1   Equipment_Name  45 non-null     object
 2   Event_Time      46 non-null     object
 3   Event_Type      46 non-null     object
 4   Status          46 non-null     object
 5   Meter_Reading   46 non-null     float64
 6   Meter_Unit      46 non-null     object
 7   Location        46 non-null     object
 8   Operator_ID     46 non-null     object
 9   Source_System   46 non-null     object
 10  Comment         31 non-null     object
dtypes: float64(1), object(10)
memory usage: 4.1+ KB

In [8]:
equipment_df.describe()

       Meter_Reading
count      46.000000
mean    22881.302174
std    147269.689798
min      1007.300000
25%      1083.950000
50%      1171.550000
75%      1253.675000
max    999999.000000

In [9]:
equipment_df.isnull().sum()

Event_ID           0
Equipment_Name     1
Event_Time         0
Event_Type         0
Status             0
Meter_Reading      0
Meter_Unit         0
Location           0
Operator_ID        0
Source_System      0
Comment           15
dtype: int64

In [14]:
duplicate_total = equipment_df.duplicated().sum()
print(f'Total number of duplicate rows: {duplicate_total}')

Total number of duplicate rows: 1

In [15]:
equipment_df.drop_duplicates(inplace=True)
duplicate_total_after = equipment_df.duplicated().sum()
print(f'Total number of duplicate rows after dropping duplicates: {duplicate_total_after}')

Total number of duplicate rows after dropping duplicates: 0